@startuml ArchLevel2

allowmixing

skinparam packageStyle rectangle
skinparam packageBackgroundColor White

package UI {
    class CLI
    class GUI
    GUI -> CLI
}

package Core {
    class ConnectionHandle
    class ConnectionIOThread
    class ConnectionManager
    ConnectionHandle --> ConnectionManager
    ConnectionManager "1" *-- "*" ConnectionIOThread
}

package Connections {
    interface Connection {
        + connect
        + disconnect
        + read
        + write
    }
    class SerialConnection {}
    class SshConnection {}
    Connection <|-- SerialConnection
    Connection <|-- SshConnection
}

UI --> ConnectionHandle
ConnectionIOThread --> Connection

@enduml
