@startuml ArchLevel2

allowmixing

skinparam packageStyle rectangle
skinparam packageBackgroundColor White

package UI {
    class CLI
}

package gRPC_server {
    class RemoteConnection {
        + CreateRemoteConnection
        + Read
        + Write
        + Stop
    }
}

package gRPC_client {
    class RemoteConnectionStub {
        + CreateRemoteConnection
        + Read
        + Write
        + Stop
    }
}

package Core {
    class ConnectionHandle
    class ConnectionIOHandle
    class ConnectionManager
     {
        + add_connection
        + subscribe
        + write_bytes
        + stop_connection
    }
    ConnectionHandle --> ConnectionManager
    ConnectionManager "1" *-- "*" ConnectionIOHandle
}

package Connections {
    interface Connection {
        + connect
        + disconnect
        + read
        + write
    }
    class SerialConnection {}
    class SshConnection {}
    Connection <|-- SerialConnection
    Connection <|-- SshConnection
}

CLI --> ConnectionHandle
gRPC_client --> gRPC_server
gRPC_server --> ConnectionManager
ConnectionIOHandle --> Connection
ConnectionManager --> Connection

@enduml
