pub mod putty_interface {
    tonic::include_proto!("putty_interface"); // generated by build.rs
}

use putty_interface::remote_connection_server::RemoteConnection;
use putty_interface::*;

use putty_core::ConnectionManager;
use putty_core::connections::connection::Connection;
use tokio::sync::mpsc;
use tonic::{Request, Response, Status};
use tracing::info;

#[derive(Clone)]
struct ConnectionService {
    manager: ConnectionManager,
}

impl ConnectionService {
    fn new(manager: ConnectionManager) -> Self {
        Self { manager }
    }
}

#[tonic::async_trait]
impl RemoteConnection for ConnectionService {
    async fn create_remote_connection(
        &self,
        req: Request<CreateRequest>,
    ) -> Result<Response<ConnectionId>, Status> {
        let id = uuid::Uuid::new_v4().to_string();
        // Unwrap the request and choose the concrete connection
        let conn: Box<dyn Connection + Send + Unpin + 'static> =
            match req
                .into_inner()
                .kind
                .ok_or_else(|| Status::invalid_argument("kind"))?
        {
            create_request::Kind::Serial(s) => Box::new(
                putty_core::connections::serial::SerialConnection::new(s.port, s.baud),
            ),
            create_request::Kind::Ssh(s) => Box::new(
                putty_core::connections::ssh::SshConnection::new(
                    s.host,
                    s.port as u16,
                    s.user,
                    s.password,
                ),
            ),
        };

        self.manager
            .add_connection(id.clone(), conn)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;

        Ok(Response::new(ConnectionId { id }))
    }

    async fn write(&self, req: Request<WriteRequest>) -> Result<Response<Empty>, Status> {
        let m = req.into_inner();
        self.manager
            .write_bytes(&m.id, &m.data)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        Ok(Response::new(Empty {}))
    }

    async fn stop(&self, req: Request<ConnectionId>) -> Result<Response<Empty>, Status> {
        self.manager
            .stop_connection(&req.into_inner().id)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        Ok(Response::new(Empty {}))
    }

    type ReadStream = tokio_stream::wrappers::ReceiverStream<Result<ByteChunk, Status>>;

    async fn read(&self, req: Request<ConnectionId>) -> Result<Response<Self::ReadStream>, Status> {
        let id = req.into_inner().id;
        let mut rx = self
            .manager
            .subscribe(&id)
            .await
            .ok_or(Status::not_found("no such connection"))?;

        let (tx, rx_stream) = mpsc::channel::<Result<ByteChunk, Status>>(64);

        // forward every chunk from ConnectionManager → gRPC stream
        tokio::spawn(async move {
            while let Ok(chunk) = rx.recv().await {
                if tx.send(Ok(ByteChunk { data: chunk })).await.is_err() {
                    break; // client hung up
                }
            }
        });

        Ok(Response::new(tokio_stream::wrappers::ReceiverStream::new(
            rx_stream,
        )))
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tracing_subscriber::fmt::init();

    let manager = ConnectionManager::new();
    let server =
        remote_connection_server::RemoteConnectionServer::new(ConnectionService::new(manager));

    info!("gRPC server listening on 0.0.0.0:50051");
    tonic::transport::Server::builder()
        .add_service(server)
        .serve(([0, 0, 0, 0], 50051).into())
        .await?;

    Ok(())
}
